version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-152-175-141.compute-1.amazonaws.com
            database: d90f3pjm6pc2p3
            schema: public
            user: xcnbopratvyvjy
            password: 0eb1c4bbc8c8db0841f7de4389e8a9883214299509d06583eaaa34df92f8a35a
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true